export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST'; 
export const FETCH_ORDERS_ERROR = 'FETCH_ORDERS_ERROR'; 
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'; 
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'; 
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

export const UPDATE_PARCEL = 'UPDATE_PARCEL';
export const UPDATE_PARCEL_REQUEST = 'UPDATE_PARCEL_REQUEST';
export const UPDATE_PARCEL_ERROR = 'UPDATE_PARCEL_ERROR';
export const UPDATE_PARCEL_SUCCESS = 'UPDATE_PARCEL_SUCCESS';

export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST';
export const UPDATE_ORDER_ERROR = 'UPDATE_ORDER_ERROR';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';

export const FETCH_ALL = 'FETCH_ALL';
